### ISSUE TITLE
SketchUp RuntimeError: bad_weak_ptr

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/openstudio-sketchup-plugin#16]
I've experienced the following error in the OS 2.6.0 and 2.8.0 SketchUp plugin with SketchUp 2018. The error occurs after importing a DXF into SU and *before* creating OpenStudio geometry.

[SketchUp 2018.skp.txt](https://github.com/NREL/OpenStudio/files/3184188/SketchUp.2018.skp.txt)

```
Error: #<RuntimeError: bad_weak_ptr>
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/RenderingColor.rb:197:in `rebuildInspectorGadget'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/RenderingColor.rb:197:in `update_entity'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:173:in `draw_entity'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:944:in `block in attach_openstudio_model'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:942:in `each'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:942:in `each_with_index'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:942:in `attach_openstudio_model'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/ModelManager.rb:227:in `attach_openstudio_model'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/ModelManager.rb:177:in `open_openstudio'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/ModelManager.rb:142:in `new_from_path'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/ModelManager.rb:117:in `new_from_skp_model'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/observers/AppObserver.rb:63:in `onOpenModel'
```

**Comment by macumber** [comment]
@MatthewSteen I just tried this using SketchUp 2019 and the new plugin and could not reproduce.  Maybe SketchUp fixed some bugs in the DXF import?

**Comment by MatthewSteen** [comment]
Ok, I'll close.
